import { readFileSync } from 'node:fs';
import { chromium } from 'playwright';
import { parseResume, buildHtml } from './scripts/build-resume.mjs';
const OUT = '/tmp/claude-1000/-home-bvinnick-mysite/3a27834d-4fa0-49e7-8f19-427bdcfb5a48/scratchpad/resume.png';
const resume = parseResume(readFileSync('./resume.md', 'utf8'));
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 701, height: 960 } });
await page.setContent(buildHtml(resume), { waitUntil: 'networkidle' });
const h = await page.evaluate(() => document.body.scrollHeight);
console.log(`HEIGHT=${h} (${h <= 960 ? 'ONE PAGE, ' + (960-h) + 'px headroom' : 'OVERFLOWS by ' + (h-960) + 'px'})`);
await page.screenshot({ path: OUT, fullPage: true });
await browser.close();
