export const resumeObj = {
  name: "Ben Vinnick",
  location: "Vancouver, BC",
  phone: "(604)-506-6024",
  email: "benvinnick@gmail.com",
  links: {
    portfolio: "https://benvinnick.com",
    github: "https://github.com/bonvee-99",
    linkedin: "https://www.linkedin.com/in/benvinnick",
  },
  workExperience: [
    {
      company: "Veeva",
      location: "Toronto, ON",
      title: "Associate Software Engineer",
      startDate: "Sept 2025",
      endDate: "Present",
      highlights: ["Working on Vault Safety Core team"],
    },
    {
      company: "CleanBill",
      location: "Vancouver, BC",
      title: "Software Developer (Contract, Part-time)",
      startDate: "April 2025",
      endDate: "Aug 2025",
      highlights: [
        "Designed and built an event-driven pipeline using Inngest and AWS Textract to automate data extraction from emergency room visit summaries for billing",
        "Developed automated workflows for MSP claim response handling, reducing human intervention",
        "Enhanced OCR parsing algorithms with orientation detection and automated note extraction from medical documents, reducing manual data entry",
      ],
    },
    {
      company: "TAIT",
      location: "Vancouver, BC (Remote)",
      title: "Software Developer Intern",
      startDate: "May 2024",
      endDate: "Aug 2024",
      highlights: [
        "Collaborated on Feltboard, a Digital CMS for the Experience Design industry",
        "Optimized storage efficiency by implementing shared media buckets, reducing redundant uploads by up to 5X",
        "Enhanced user workflow by creating a “save as” feature, allowing users to easily replicate and modify data structures",
        "Implemented media replacement for seamless content updates without disruption",
      ],
    },
    {
      company: "TAIT",
      location: "Vancouver, BC (Remote)",
      title: "Software Developer Intern",
      startDate: "July 2022",
      endDate: "Aug 2023",
      highlights: [
        "Developed a frontend dashboard using Vue to allow users to monitor key metrics within their connected devices",
        "Facilitated dynamic schema relationships within the backend, empowering users to create and manage intricate content structures",
        "Deployed an image resize proxy using Docker, Nginx, and GKE to reduce service strain and optimize page load times",
      ],
    },
    {
      company: "University of British Columbia",
      location: "Vancouver, BC",
      title: "Teaching Assistant",
      startDate: "Sept 2021",
      endDate: "Dec 2022",
      highlights: [
        "Taught fundamental programming skills and concepts such as recursion, graph traversal, testing, and debugging",
        "Received a 100% favourable rating from over 70 students",
        "Led weekly labs and office hours for over 1200 students across three academic semesters",
      ],
    },
  ],
  projects: [
    {
      title: "Sports Macros",
      link: "https://bonvee-nhl-macros.s3.us-west-1.amazonaws.com/dist/index.html",
      date: "Oct 2021 - Present",
      highlights: [
        "Independently created a web application with TypeScript, tailored for media professionals",
        "Facilitates effortless generation of macros, optimizing the media captioning workflow within Photo Mechanic",
        "Utilized by professional NHL photographers during every Vancouver Canucks home game for the past 3 seasons",
      ],
    },
    {
      title: "DLS",
      link: "https://github.com/bonvee-99/dls",
      date: "July 2023",
      highlights: [
        "Co-created a Rust CLI designed for secure secret sharing among developers over WebSockets",
        "Implemented end-to-end encryption using RSA public/private key pairs",
        "Introduced the ability for users to join rooms through dynamically generated URLs",
      ],
    },
  ],
  education: {
    school: "University of British Columbia",
    location: "Vancouver, BC",
    degree: "Bachelor of Science, Computer Science",
    faculty: "Science",
    startDate: "Sept 2019",
    endDate: "April 2025",
    gpa: "84%",
    coursework: [],
  },
  skills: {
    languages: [
      "Java",
      "Python",
      "TypeScript",
      "JavaScript",
      "Bash",
      "SQL",
      "NoSQL",
      "GraphQL",
      "HTML",
      "CSS",
    ],
    frameworks: ["Node", "React / Next", "Vue", "JUnit", "Mocha", "Chai"],
    other: [
      "Git",
      "Docker",
      "Kubernetes",
      "GCP",
      "AWS",
      "Terraform",
      "Jenkins",
      "Datadog",
      "Jira",
    ],
  },
};
